### ISSUE TITLE
@keyframes rules appear in both or neither output files depending on inside declarations

### ISSUE THREAD

**Issue by Jonax** [mrnocreativity/postcss-critical-split#10]
A @keyframes rule marked as critical will appear in both _critical_ & _rest_ CSS output if the rule in question contains declarations.  Alternatively, a @keyframes rule will feature in neither if lacking declarations.  

*input.css*
```css
/* critical:start */
@keyframes neitherA
{
	50%
	{
	}
}
/* critical:end */

/* critical:start */
@keyframes neitherB
{
	from
	{
	}

	to
	{
	}
}
/* critical:end */

/* critical:start */
/* From https://developer.mozilla.org/en-US/docs/Web/CSS/%40keyframes */
@keyframes bothA
{
	from
	{
		margin-left: 100%;
		width: 300%;
	}

	to
	{
		margin-left: 0%;
		width: 100%;
	}
}
/* critical:end */

/* critical:start */
@keyframes bothB
{

	0%, 80%, 100%
	{
		transform:	scale(0);
	}

	40%
	{
		transform:	scale(1);
	}
}
/* critical:end */
```

neitherA & neitherB appear in neither _critical_ or _rest_ output.  bothA & bothB appear in both.  

Repro case was ran through gulp-postcss with no other plugins used.  Modules used include:
- Node v8.9.4
- Gulp v4.0
- gulp-postcss v.7.0.1
- postcss-critical-split v2.5.1

I tried having a dig in the code in the hopes of providing a PR, but had some difficulty figuring the overall flow (e.g. appendDeclaration() vs appendFullBlock()).  Closest I could find is that all affected cases seem to trigger the following condition in getAllCriticals():

```javascript
  } else if (criticalActive === true && (line.type === 'decl' && hasParentAtRule(line, 'keyframes') === true)) {
    // ignore this rule...
```
