### ISSUE TITLE
Important comments support bug with start/end tags

### ISSUE THREAD

**Issue by agarzola** [mrnocreativity/postcss-critical-split#17]
Given the following CSS file:
```css
/*! critical:start */
header {
  background-color: orange;
}

/*! critical:end */
p {
  background-color: blue;
}

/*# sourceMappingURL=test.css.map */
/* v19.04.19 +4 (c00d698d) */
```

I get the following critical CSS:
```css
header {
  background-color: orange;
}

/*! critical:end */

p {
  background-color: blue;
}

/* v19.04.19 +4 (c00d698d) */
```

It appears that, for some reason, `critical:end` is not detected when using the “important comment” syntax (`/*! */`) preferred by Sass linters. I see support for this was added in response to #11. Was it intended to work with start/end tags?
