### ISSUE TITLE
[Question] Split into Multiple Files?

### ISSUE THREAD

**Issue by OwenMelbz** [mrnocreativity/postcss-critical-split#8]
Hi, we're looking to try use this package in our workflow and wondering if its currently possible to split the critical css out into different files?

I know the below syntax is already taken, but is it possible for something like:

Imagine this is your `app.css`

```css
body {
  background: red;

  /* critical:start */
  height: 400px;
  /* critical:end */

  /* critical:start:home */
  color: red;
  /* critical:end */

  /* critical:start:work */
  width: 200px;
  /* critical:end */
}

```

The theory being you'd end up with 4 css files

- app.css
- critical.css
- critical-home.css
- critical-work.css

Is this possible? Thanks
